name: Print Software Versions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  check-application-layer-software:
    runs-on: ubuntu-latest
    steps:
      - name: Check Python version
        run: python3 --version

      - name: Check Flask version
        run: |
          pip install flask
          python3 -c "import flask; print('Flask', flask.__version__)"

  check-database-layer-software:
    runs-on: ubuntu-latest
    needs: check-application-layer-software
    steps:
      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Check PostgreSQL version
        run: psql --version
